CREATE TABLE UPLOADED_VIDEOS (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100),
	creator_id INTEGER NOT NULL,
	object_key VARCHAR(136),
	uploaded BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP(6) WITH TIME ZONE,
	share_url VARCHAR(100),
	short_url_hash VARCHAR(8),
	original_url VARCHAR(600),
	expires_in TIMESTAMP(6) WITH TIME ZONE,
	CONSTRAINT fk_uploaded_video_creator FOREIGN KEY (creator_id) REFERENCES USERS(id)
);

CREATE INDEX short_url_hash_index ON UPLOADED_VIDEOS (short_url_hash);

CREATE INDEX creator_id_index ON UPLOADED_VIDEOS (creator_id);