version: "3"
services:
  postgres:
    image: postgres:17
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: fileshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2GB"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    volumes:
      - emaildata:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  garage:
    image: dxflrs/garage:v1.0.1
    ports:
      - "3900:3900"
      - "3902:3902"
      - "3903:3903"
    environment:
      RUST_LOG: info
      GARAGE_RPC_SECRET: 376ead8159bfada1e3317bf3e3ad945eff9184b7ea18d2ba0b46261241b243ad
    command: /garage -c /etc/garage.toml server
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    healthcheck:
      test: ["CMD", "/garage", "-c", "/etc/garage.toml", "status"]
      interval: 5s
      timeout: 3s
      retries: 10

  garage_init:
    image: alpine:latest
    depends_on:
      garage:
        condition: service_healthy
    environment:
      DOCKER_API_VERSION: "1.41"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scripts/garage-init.sh:/init.sh:ro
      - ./scripts/configure-cors.py:/configure-cors.py:ro
    entrypoint: ["sh", "/init.sh"]

volumes:
  emaildata:
  postgres-data:
