{
 "title": "Logs Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(app)" },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"$app\"} \r\n| json \r\n|= \"$search\" \r\n| line_format \"{{.level}} {{.message}} trace={{.traceId}}\""
    }
   ]
  },
  {
   "title": "Logs por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time({app=~\"$app\"}[1m])"
    }
   ]
  },
  {
   "title": "Erros por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time({app=~\"$app\", level=\"ERROR\"}[1m])"
    }
   ]
  }
 ]
}